/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import modelo.Usuario;

public class MenuPrincipal extends javax.swing.JFrame {
    public Usuario usuario;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Usuario u) {
        this.usuario = u;
        initComponents();
        String funçao = u.getFunçao();
          if (funçao.equals("Outro")){
              jBeditarLocais.setVisible(false);
          }
          else if (funçao.equals("Gestor de recursos")){
              jBeditarLocais.setVisible(false);
              jBagendarReuniao.setVisible(false);
              jBreunioesAnteriores.setVisible(false);
              jBConfirmarPres.setVisible(false);
              jBeditarAta.setVisible(false);
              jBeditarPartici.setVisible(false);
          }
    }
    public MenuPrincipal() {
        initComponents();
    }
    
    
    //TeladeLogin.get(uLogin).getFunçao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBagendarReuniao = new javax.swing.JButton();
        jBreunioesAnteriores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLProximasreunioes = new javax.swing.JLabel();
        jBConfirmarPres = new javax.swing.JButton();
        jBeditarAta = new javax.swing.JButton();
        jBeditarPartici = new javax.swing.JButton();
        jBeditarLocais = new javax.swing.JButton();
        jBconfirmarLocais = new javax.swing.JButton();
        jBcadastrarLocais = new javax.swing.JButton();
        jbSair1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBagendarReuniao.setText("Agendar Reunião");
        jBagendarReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagendarReuniaoActionPerformed(evt);
            }
        });

        jBreunioesAnteriores.setText("Reuniões anteriores");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLProximasreunioes.setText("Proximas reuniões: ");

        jBConfirmarPres.setText("Confirmar Presença");
        jBConfirmarPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarPresActionPerformed(evt);
            }
        });

        jBeditarAta.setText("Editar Ata");

        jBeditarPartici.setText("Editar Participantes");

        jBeditarLocais.setText("Editar Locais");

        jBconfirmarLocais.setText("Confirmar Locais");

        jBcadastrarLocais.setText("Cadastrar Locais");

        jbSair1.setBackground(new java.awt.Color(204, 0, 0));
        jbSair1.setText("LOGOFF");
        jbSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSair1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBeditarPartici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBeditarAta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBreunioesAnteriores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBagendarReuniao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBConfirmarPres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jbSair1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProximasreunioes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBeditarLocais)
                            .addComponent(jBconfirmarLocais)
                            .addComponent(jBcadastrarLocais))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbSair1)
                .addGap(16, 16, 16)
                .addComponent(jLProximasreunioes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBagendarReuniao)
                            .addGap(18, 18, 18)
                            .addComponent(jBreunioesAnteriores)
                            .addGap(18, 18, 18)
                            .addComponent(jBConfirmarPres)
                            .addGap(18, 18, 18)
                            .addComponent(jBeditarAta)
                            .addGap(18, 18, 18)
                            .addComponent(jBeditarPartici))
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBconfirmarLocais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBcadastrarLocais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBeditarLocais)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBagendarReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagendarReuniaoActionPerformed
new AgendarReuniao().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jBagendarReuniaoActionPerformed

    private void jBConfirmarPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarPresActionPerformed
       new ConfirmarPresença().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jBConfirmarPresActionPerformed

    private void jbSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSair1ActionPerformed
new TeladeLogin().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jbSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmarPres;
    private javax.swing.JButton jBagendarReuniao;
    private javax.swing.JButton jBcadastrarLocais;
    private javax.swing.JButton jBconfirmarLocais;
    private javax.swing.JButton jBeditarAta;
    private javax.swing.JButton jBeditarLocais;
    private javax.swing.JButton jBeditarPartici;
    private javax.swing.JButton jBreunioesAnteriores;
    private javax.swing.JLabel jLProximasreunioes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbSair1;
    // End of variables declaration//GEN-END:variables
}
